apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  signature-server-listener-interceptor
  name: signature-server-listener-route
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-signature-server-listener-interceptor
