apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: signature-server-trigger-pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: service-account
    description: The ServiceAccount under which to run the Pipeline.
  - name: args
    description: arguments for the oc task
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-signature-server-pr-tr-
    spec:
      serviceAccountName: $(params.service-account)
      pipelineRef:
        name: build-signature-server
      params:
      - name: args
        value:
        - start-build
        - signature-server
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
